In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(
    r"S:\DA  notes\census+income\adult.data",
    header=None,
    skipinitialspace=True
)

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

### EDA (Exploratory Data Analysis)

In [5]:
# Definition: EDA is the process of examining and understanding a dataset before applying data analysis or machine learning.
# Use: To understand the data, find missing values, identify outliers, and discover patterns.
#-----
# EDA - Exploratory Data Analysis
# Def:
# EDA is an approach used to analyze datasets and summarize their characteristics.
# EDA helps to understand the dataset, identify patterns and distributions, and detect outliers.

#### Major Operations Performed During Exploratory Data Analysis (EDA)

In [6]:
# Major Operations Performed During Exploratory Data Analysis (EDA)
# 1. Understanding the Dataset
# 2. Indexing and Filtering
# 3. Statistical Analysis of the Dataset
# 4. Identifying NaN (Missing) Values
# 5. Identifying Duplicate Values
# 6. Identifying Outliers

##### Data cleaning

In [7]:
# Major Data Cleaning Operations
# 1. Fixing Data Inconsistencies
# 2. Handling NaN (Missing) Values
# 3. Handling Duplicate Values
# 4. Handling Outliers

##### Mini Project: Student Performance Analysis

###### Load the dataset

In [8]:
import os
os.getcwd()

'C:\\Users\\admin\\ DA  notes'

In [11]:
import os
os.path.exists(r"S:\DA  notes\census+income\adult.data")

True

###### Data Cleaning: Handling Data Inconsistencies

In [12]:
cols = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", 
        "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", 
        "native-country", "income"]
len(cols)

15

In [14]:
df = pd.read_csv(
    r"S:\DA  notes\census+income\adult.data",
    names=cols,
    skipinitialspace=True
)

df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

###### 1. Understanding the Dataset

In [15]:
# df.head() – Displays the first 5 rows.
# df.tail() – Displays the last 5 rows.
# df.shape – Returns the number of rows and columns.
# df.columns – Displays all column names.
# df.dtypes – Shows the data type of each column.
# df.info() – Shows column names, data types, and non-null counts.
# df.describe() – Displays statistical information about numerical columns.
# df.isnull().sum() – Counts missing values in each column.
# df.duplicated().sum() – Counts duplicate rows.
# df.nunique() – Counts unique values in each column.

In [16]:
df.shape

(32561, 15)

In [17]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [18]:
df.tail() # to give random values
df.sample(5)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
5188,33,Private,124187,11th,7,Never-married,Transport-moving,Not-in-family,Black,Male,0,0,60,United-States,<=50K
25517,27,Private,204098,10th,6,Never-married,Craft-repair,Not-in-family,White,Male,0,0,30,United-States,<=50K
423,29,Private,188401,HS-grad,9,Divorced,Farming-fishing,Not-in-family,White,Male,0,0,40,United-States,<=50K
5079,53,Private,127671,7th-8th,4,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
15277,31,Private,207685,HS-grad,9,Never-married,Other-service,Unmarried,Black,Female,0,0,34,United-States,<=50K

In [19]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

###### Printing Categorical Column Names

In [21]:
# Printing Categorical Column Names
df.select_dtypes(include='object').columns

Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'native-country', 'income'],
      dtype='object')

###### Printing Numerical Column Names

In [22]:
# printing numerical column names
df.select_dtypes(include = 'int').columns

Index(['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss',
       'hours-per-week'],
      dtype='object')

###### Providing Statistical Information

In [23]:
# Providing Statistical Information
# Definition:
# Statistical information summarizes numerical data to understand its
# average, spread, and range.
# Important Points:
# 1. count - Number of non-missing values.
# 2. mean - Average value.
# 3. std - Measures the spread of values.
# 4. min and max - Smallest and largest values.
# 5. 25%, 50%, 75% - Quartiles used to understand data distribution.
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [24]:
# Providing Statistical Information for Categorical Columns
# Definition:
# Statistical information for categorical columns summarizes text data
# and shows the frequency of unique values.
# Important Points:
# 1. count - Number of non-missing values.
# 2. unique - Number of distinct values.
# 3. top - Most frequently occurring value.
# 4. freq - Frequency of the most common value.
# 5. include='object' - Selects columns with the object data type.

df.describe(include='object')

,workclass,education,marital-status,occupation,relationship,race,sex,native-country,income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,22696,10501,14976,4140,13193,27816,21790,29170,24720

In [25]:
# Providing Statistical Information for All Columns
# Definition:
# df.describe(include='all') provides a statistical summary of both
# numerical and categorical columns in a dataset.
# Important Points:
# 1. Numerical columns - Displays count, mean, std, min, quartiles, and max.
# 2. Categorical columns - Displays count, unique, top, and freq.
# 3. NaN values - Some statistics may show NaN when they are not applicable.
# 4. include='all' - Includes all column data types.

df.describe(include='all')

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
count,32561.000000,32561,3.256100e+04,32561,32561.000000,32561,32561,32561,32561,32561,32561.000000,32561.000000,32561.000000,32561,32561
unique,NaN,9,NaN,16,NaN,7,15,6,5,2,NaN,NaN,NaN,42,2
top,NaN,Private,NaN,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,22696,NaN,10501,NaN,14976,4140,13193,27816,21790,NaN,NaN,NaN,29170,24720
mean,38.581647,NaN,1.897784e+05,NaN,10.080679,NaN,NaN,NaN,NaN,NaN,1077.648844,87.303830,40.437456,NaN,NaN
std,13.640433,NaN,1.055500e+05,NaN,2.572720,NaN,NaN,NaN,NaN,NaN,7385.292085,402.960219,12.347429,NaN,NaN
min,17.000000,NaN,1.228500e+04,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,1.178270e+05,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,1.783560e+05,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,2.370510e+05,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,1.484705e+06,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

In [26]:
# Finding Unique Values in a Categorical Column
# Definition:
# unique() returns all distinct values present in a column.
# Important Points:
# 1. Displays each unique value only once.
# 2. Helps identify different categories in a column.
# 3. Useful for detecting inconsistent values during data cleaning.
# 4. NaN may also appear if missing values exist.

df['marital-status'].unique()

array(['Never-married', 'Married-civ-spouse', 'Divorced',
       'Married-spouse-absent', 'Separated', 'Married-AF-spouse',
       'Widowed'], dtype=object)

In [27]:
# Finding Unique Values in Workclass
# Definition: Returns all distinct values in the workclass column.
# Importance: Helps identify categories and inconsistencies.

df.workclass.unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [30]:
# Removing Extra Spaces from Workclass
# Definition: strip() removes leading and trailing spaces.
# Importance: Helps maintain consistent categorical values.

df.workclass = df.workclass.str.strip()

In [31]:
# Checking Unique Values After Cleaning
# Definition: Displays distinct values in the workclass column.
# Importance: Verifies whether extra spaces have been removed.

df.workclass.unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [32]:
# Replacing '?' with Missing Values
# Definition: Replaces '?' with NaN.
# Importance: Helps identify and handle missing values.

import numpy as np
df.workclass = df.workclass.replace('?', np.nan)

In [33]:
# Checking Unique Values After Replacing '?' with NaN
# Definition: Displays distinct values in the workclass column.
# Importance: Verifies that '?' has been replaced with NaN.

df.workclass.unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', nan, 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [34]:
# Removing Extra Spaces from Marital Status
# Definition: Removes leading and trailing spaces.
# Importance: Maintains consistent categorical values.

df['marital-status'] = df['marital-status'].str.strip()

In [35]:
# Checking Unique Marital Status Values
# Definition: Displays all distinct values in the column.
# Importance: Checks categories after removing extra spaces.

df['marital-status'].unique()

array(['Never-married', 'Married-civ-spouse', 'Divorced',
       'Married-spouse-absent', 'Separated', 'Married-AF-spouse',
       'Widowed'], dtype=object)

In [36]:
# Checking Unique Education Values
# Definition: Displays all distinct values in the education column.
# Importance: Helps identify categories and inconsistencies.

df['education'].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

In [37]:
# Removing Extra Spaces from Education
# Definition: Removes leading and trailing spaces.
# Importance: Maintains consistent category values.

df['education'] = df['education'].str.strip()

In [38]:
# Checking Unique Education Values
# Definition: Displays distinct values in the education column.
# Importance: Verifies categories after removing extra spaces.

df['education'].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

In [39]:
# Checking Unique Occupation Values
# Definition: Displays all distinct values in the occupation column.
# Importance: Helps identify categories and inconsistencies.

df['occupation'].unique()

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing', 'Machine-op-inspct',
       'Tech-support', '?', 'Protective-serv', 'Armed-Forces',
       'Priv-house-serv'], dtype=object)

In [40]:
# Removing Extra Spaces from Occupation
# Definition: Removes leading and trailing spaces.
# Importance: Maintains consistent category values.

df['occupation'] = df['occupation'].str.strip()

In [41]:
df['occupation'].unique()

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing', 'Machine-op-inspct',
       'Tech-support', '?', 'Protective-serv', 'Armed-Forces',
       'Priv-house-serv'], dtype=object)

In [42]:
# Replacing '?' with NaN in Occupation
# Definition: Replaces '?' with a missing value.
# Importance: Helps identify and handle missing data.

df.occupation = df.occupation.replace('?', np.nan)

In [43]:
df['occupation'].unique()

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing', 'Machine-op-inspct',
       'Tech-support', nan, 'Protective-serv', 'Armed-Forces',
       'Priv-house-serv'], dtype=object)

In [45]:
# Checking Unique Relationship Values
# Definition: Displays distinct values in the relationship column.
# Importance: Helps identify categories and inconsistencies.

df['relationship'].unique()

array(['Not-in-family', 'Husband', 'Wife', 'Own-child', 'Unmarried',
       'Other-relative'], dtype=object)

In [46]:
# Removing Extra Spaces from Relationship
# Definition: Removes leading and trailing spaces.
# Importance: Maintains consistent category values.

df['relationship'] = df['relationship'].str.strip()

In [47]:
df['relationship'].unique()

array(['Not-in-family', 'Husband', 'Wife', 'Own-child', 'Unmarried',
       'Other-relative'], dtype=object)

In [48]:
# Checking Unique Race Values
# Definition: Displays distinct values in the race column.
# Importance: Helps identify categories and inconsistencies.

df['race'].unique()

array(['White', 'Black', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo',
       'Other'], dtype=object)

In [49]:
df['race'] = df['race'].str.strip()

In [50]:
df['native-country'].unique()

array(['United-States', 'Cuba', 'Jamaica', 'India', '?', 'Mexico',
       'South', 'Puerto-Rico', 'Honduras', 'England', 'Canada', 'Germany',
       'Iran', 'Philippines', 'Italy', 'Poland', 'Columbia', 'Cambodia',
       'Thailand', 'Ecuador', 'Laos', 'Taiwan', 'Haiti', 'Portugal',
       'Dominican-Republic', 'El-Salvador', 'France', 'Guatemala',
       'China', 'Japan', 'Yugoslavia', 'Peru',
       'Outlying-US(Guam-USVI-etc)', 'Scotland', 'Trinadad&Tobago',
       'Greece', 'Nicaragua', 'Vietnam', 'Hong', 'Ireland', 'Hungary',
       'Holand-Netherlands'], dtype=object)

In [51]:
df['native-country'] = df['native-country'].str.strip()

In [52]:
df['native-country'] = df['native-country'].replace('?', np.nan)

In [53]:
df['native-country'].unique()

array(['United-States', 'Cuba', 'Jamaica', 'India', nan, 'Mexico',
       'South', 'Puerto-Rico', 'Honduras', 'England', 'Canada', 'Germany',
       'Iran', 'Philippines', 'Italy', 'Poland', 'Columbia', 'Cambodia',
       'Thailand', 'Ecuador', 'Laos', 'Taiwan', 'Haiti', 'Portugal',
       'Dominican-Republic', 'El-Salvador', 'France', 'Guatemala',
       'China', 'Japan', 'Yugoslavia', 'Peru',
       'Outlying-US(Guam-USVI-etc)', 'Scotland', 'Trinadad&Tobago',
       'Greece', 'Nicaragua', 'Vietnam', 'Hong', 'Ireland', 'Hungary',
       'Holand-Netherlands'], dtype=object)

In [54]:
df['sex'].unique()

array(['Male', 'Female'], dtype=object)

In [55]:
df['sex'] = df['sex'].str.strip()

In [56]:
df['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [57]:
df['income'] = df['income'].str.strip()

In [58]:
df['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [59]:
# Removing Extra Spaces from All Text Columns
# Definition: Removes leading and trailing spaces from object columns.
# Importance: Cleans text data and maintains consistent values.

df = df.apply(lambda col: col.str.strip() if col.dtype == 'object' else col)

######  EDA-2: 2. Indexing and Filtering

In [60]:
# EDA-2: 2. Indexing and Filtering
# Definition:
# Indexing selects specific rows or columns.
# Filtering selects rows that satisfy a given condition.
# Importance:
# 1. Helps access required data.
# 2. Helps analyze specific records.
# 3. Helps find data based on conditions.

In [61]:
# Displaying Column Names
# Definition: Shows all column names in the dataset.
# Importance: Helps identify columns for indexing and filtering.

df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [62]:
# Selecting Rows and Columns Using loc
# Definition: Selects data using row labels and column names.
# Important: The ending labels are included.

df.loc[1:6, 'age':'education']

   age         workclass  fnlwgt  education
1   50  Self-emp-not-inc   83311  Bachelors
2   38           Private  215646    HS-grad
3   53           Private  234721       11th
4   28           Private  338409  Bachelors
5   37           Private  284582    Masters
6   49           Private  160187        9th

In [63]:
# Selecting Rows and Columns Using iloc
# Definition: Selects data using integer positions.
# Important: The stop index is excluded.

df.iloc[1:7, 0:4]

   age         workclass  fnlwgt  education
1   50  Self-emp-not-inc   83311  Bachelors
2   38           Private  215646    HS-grad
3   53           Private  234721       11th
4   28           Private  338409  Bachelors
5   37           Private  284582    Masters
6   49           Private  160187        9th

In [64]:
# Selecting Specific Columns Using iloc
# Definition: Selects rows and specific columns by position.
# Important: Column positions 0 and 3 are selected.

df.iloc[1:7, [0, 3]]

   age  education
1   50  Bachelors
2   38    HS-grad
3   53       11th
4   28  Bachelors
5   37    Masters
6   49        9th

In [65]:
# Selecting Specific Columns Using loc
# Definition: Selects rows and columns using labels.
# Important: The ending row label is included.

df.loc[1:6, ['age', 'education']]

   age  education
1   50  Bachelors
2   38    HS-grad
3   53       11th
4   28  Bachelors
5   37    Masters
6   49        9th

In [66]:
# Filtering Records Where Age Is Less Than 20
# Definition: Selects rows where the age is below 20.
# Importance: Helps find records that meet a specific condition.

df[df.age < 20]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
37,19,Private,544091,HS-grad,9,Married-AF-spouse,Adm-clerical,Wife,White,Female,0,0,25,United-States,<=50K
51,18,Private,226956,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,30,NaN,<=50K
70,19,Private,101509,Some-college,10,Never-married,Prof-specialty,Own-child,White,Male,0,0,32,United-States,<=50K
78,18,Private,309634,11th,7,Never-married,Other-service,Own-child,White,Female,0,0,22,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32392,18,Private,200047,12th,8,Never-married,Adm-clerical,Own-child,White,Male,0,0,35,United-States,<=50K
32437,19,Private,60890,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0,0,49,United-States,<=50K
32443,18,Private,41381,HS-grad,9,Never-married,Sales,Own-child,White,Female,0,1602,20,United-States,<=50K
32447,17,Private,117798,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,20,United-States,<=50K
32496,18,Private,436163,11th,7,Never-married,Prof-specialty,Own-child,White,Male,0,0,20,United-States,<=50K

In [67]:
# Filtering Records Where Age Is Between 20 and 40
# Definition: Selects records where age is greater than 20 and less than 40.
# Important: & means AND; both conditions must be true.

df[(df.age > 20) & (df.age < 40)]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [68]:
# Filtering Records Where Age Is Greater Than 20 OR Less Than 40
# Definition: Selects records that satisfy at least one condition.
# Important: | means OR; either condition can be true.

df[(df.age > 20) | (df.age < 40)]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K